### ISSUE TITLE
IBEA documentation

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyOpt#101]
At description of how the evolutionary algorithm works to the documentation

**Comment by tapaswenipathak** [comment]
Hi @wvangeit, I think this is already completed https://github.com/BlueBrain/BluePyOpt/blob/master/l5pc/opt_l5pc.py. Does this ticket requires adding the docs in `BluePyOpt/docs/source/optimisations.rst`?

**Comment by tapaswenipathak** [comment]
Hi @wvangeit -

Does this ticket requires adding the docs in `BluePyOpt/docs/source/optimisations.rst`?

**Comment by tapaswenipathak** [comment]
@wvangeit gentle re-ping in case you missed this ping.

**Comment by tapaswenipathak** [comment]
@wvangeit gentle reminder in case you missed this ping.
