### ISSUE TITLE
Create test that runs L5PC optimisation

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyOpt#12]
Atm the L5PC test only creates and runs the template and imports the optimisation.
There should be a functionality test that runs a tiny optimisation (using scoop).

**Comment by mgeplf** [comment]
I'll have a go at this if you haven't already started

**Comment by wvangeit** [comment]
Ok, no I havent started yet. We just need like 1 or two 2 generations and 2 offspring. We could also make the stimuli shorter and/or remove stimuli.

**Comment by mgeplf** [comment]
I did one for the simplecell:
https://github.com/BlueBrain/BluePyOpt/pull/14/files

I'll do an l5pc one tmrw.
