### ISSUE TITLE
cvode_minstep not reset after running protocol

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyOpt#134]
After a protocol that sets cvode_minstep is run, this variable is not reset to it's original state. This can create problems if other protocols don't use cvode_minstep

**Comment by tapaswenipathak** [comment]
I think this is [fixed](https://github.com/BlueBrain/BluePyOpt/search?utf8=%E2%9C%93&q=cvode_minstep&type=) currently?

**Comment by tapaswenipathak** [comment]
@wvangeit gentle re-ping in case you missed this ping.

**Comment by tapaswenipathak** [comment]
@wvangeit gentle reminder in case you missed this ping.

**Comment by wvangeit** [comment]
@DrTaDa, could you check this?

**Comment by DrTaDa** [comment]
@wvangeit, the same simulator is used by all the protocols since the sim attribute belong to the CellEvaluator, so all the protocols use the same cvode_minstep. 

Does it happen that a protocol itself change the cvode_minstep value ?

**Comment by wvangeit** [comment]
Yes, I think it would be possible that different protocols use different cvode_minstep
