### ISSUE TITLE
HocModel constructor signature needs to be changed

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyOpt#146]
Needs to allow for:
- hoc code should be read from string (See #143). hoc_path is not necessary anymore. Should be first argument after name.
- we need a morph_dir argument to specify morphology directory. when this is specified morph filename in hoc can be used.
- morph_filename, overwrite morph_filename specified in hoc 
- hoc code should not have full path to morpho anymore (only morph_filename)
- have an argument extra_params which is a list of (e.g. Global) parameters that have to be set outside of the hoc template, like celsius / v_init etc.

We could slowly change by calling the class with the above constructor 'HocCellModel' (that should be the name anyway). Then we can phase out slowly the HocModel.

**Comment by mgeplf** [comment]
So, to be clear, you want the current initializer:
`def __init__(self, name, morphology_path, hoc_path):`

To be:
`def __init__(self, name, hoc_string, morph):`

where morph is a `HocMorphology` with initializer:
`def __init__(self, name, morph_dir=None, morph_name=None, delete_axon_hoc=None)`

The last point has been addressed by #148.

**Comment by wvangeit** [comment]
Mmm, no, I was rather thinking of:

def __init__(self, name, hoc_string, morph_dir=None, morph_name=None)

the delete_axon hoc code should be extracted by CellModel from it NrnFileMorphology when .create_hoc() is called

**Comment by mgeplf** [comment]
Ok.  What do you want the behavior of `morph_dir=None, morph_name=None` to be?
* MD=None, MN=None?
* MD=None, MN='foo.asc'?
* MD='somedir', MN=None?
* MD='somedir', MN='foo.asc'?

**Comment by mgeplf** [comment]
Actually, is there any benefit compared to the current way? I can split the the morphology_path intelligently to dirname/basename, no?
