### ISSUE TITLE
load morphologies from hoc files rather than swc or asc files

### ISSUE THREAD

**Issue by yan1982** [BlueBrain/BluePyOpt#159]
Hello,
I would like to optimize parameters of a single compartment from some experimental data. Instead of describing morphology in swf or asc files, I'd rather do it in a hoc file. How I can make it from one of the functions or classes provided by the bluepyopt.ephys Module?

thank

**Comment by wvangeit** [comment]
Hi @yan1982, you don't need this feature anymore ?

**Comment by yan1982** [comment]
I always need this feature. I closed this issue by mistake.

**Comment by wvangeit** [comment]
One option would be to provide your own Morphology class that creates the single compartment. You could base the class on the one defined here: https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/morphologies.py
If you provide me we an example of an hoc morphology description you want to use, I can make an example for you

**Comment by yan1982** [comment]
@wvangeit , thank for your answer. Hoc file that I send you in attached file contain geometry of single compartment with stylised method rather than 3D-method.
[morpho.txt](https://github.com/BlueBrain/BluePyOpt/files/481832/morpho.txt)

**Comment by wvangeit** [comment]
Hi,
Is it sufficient if I provide you with a little script you can use to create an SWC morphology with the dimensions you need ? 
I've attached such a script to this comment.
The way you use it is as follows, e.g.:
python create_soma.py --L=10 --diam=5 --filename='soma.swc'

[create_swc_soma.py.zip](https://github.com/BlueBrain/BluePyOpt/files/486687/create_swc_soma.py.zip)

**Comment by yan1982** [comment]
Ok thank. I think it should normally be sufficient. I'll try it.

**Comment by wvangeit** [comment]
Btw, just saw I made a small mistake in the commandline example, it should be:
python create_swc_soma.py --L=10 --diam=5 --filename='soma.swc'

**Comment by wvangeit** [comment]
Hi @yan1982, did you manage to run the script ? 
Is this solution sufficient for you, and can I close the issue ?

**Comment by yan1982** [comment]
Hi @wvangeit , yes it work for me. The issue can be closed.

**Comment by wvangeit** [comment]
Ok, great.
