### ISSUE TITLE
 opt_l5pc.py: problem with importing an internal module simulators.

### ISSUE THREAD

**Issue by russelljjarvis** [BlueBrain/BluePyOpt#187]
I have tried to get started and to explore this issue by reproducing the examples in the example folder. I compiled the appropriate `nmodl` mechanisms with 

 ```/work/scidash/BluePyOpt/examples/l5pc/mechanisms$ nrnivmodl``` 

I have both scoop and ipyparallel installed. However I just launch opt_l5pc.py without any flags first because it exposes the most fundamental error messages.

When I run the command:
```
jovyan@650b8092666a:~/work/scidash/BluePyOpt/examples/l5pc$ python opt_l5pc.py 
```

I get the output below. Is there particular branch of bluepyopt that contains a simulator module? If its an external module I wonder where I can get it?

```
Traceback (most recent call last):
  File "opt_l5pc.py", line 44, in <module>
    import l5pc_evaluator
  File "/home/jovyan/work/scidash/BluePyOpt/examples/l5pc/l5pc_evaluator.py", line 26, in <module>
    import l5pc_model  # NOQA
  File "/home/jovyan/work/scidash/BluePyOpt/examples/l5pc/l5pc_model.py", line 26, in <module>
    import bluepyopt.ephys as ephys
  File "/opt/conda/lib/python3.5/site-packages/bluepyopt-1.2.87-py3.5.egg/bluepyopt/ephys/__init__.py", line 24, in <module>
    import simulators  # NOQA
ImportError: No module named 'simulators'
```

Thanks.
Russell.

**Comment by wvangeit** [comment]
Hi @russelljjarvis,
I saw you are using python 3.5. At the moment BluePyOpt doesn't support Python 3 (yet), and this what's causing this strange error.
We're working on getting a py3 version of BluePyOpt running, but in the mean time, please use python 2.

**Comment by wvangeit** [comment]
@russelljjarvis, I committed code to make BluePyOpt compatible with Python 3. (So when you upgrade to the latest version of BluePyOpt you should be to run it in py3.)
Just to be sure it is advised to use Python 3.6. The tests caused strange segfaults in Python 3.4 and 3.5, I'm still not sure what was going on, but Python 3.6 doesn't seem to have this issue.

**Comment by russelljjarvis** [comment]
Hi Wvangeit. No I was not able to easily try it with python-3.6

I am using a docker scipy base available [here]([https://github.com/scidash/docker-stacks/tree/master/neuronunit-scoop-deap](url)) 

I tried to add in lines to build python3.6 but starting from the scipy stacks foundation by adding in all of these docker lines.

RUN wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz
RUN tar xvf Python-3.6.0.tgz
WORKDIR Python-3.6.0
RUN apt-get install -y zlib1g-dev 
RUN ./configure --enable-optimizations
RUN make -j8
RUN make altinstall
RUN python3.6

Python-3.6 builds okay, but then the BluePyOpt build because it needs future, jinja2, and something else. I was able to gitclone install future and jinja2, however this process seemed like it wouldn't end and I decided to give up. Sorry.

**Comment by wvangeit** [comment]
Hi @russelljjarvis. Are you also installing bluepyopt using the docker config file, or manually afterwards. 
When you say 'however this process seemed like it wouldn't end', do you know during which step this happens. Is it during the install of future/jinja, one of the other dependencies of bluepyopt, or bluepyopt itself ?

**Comment by russelljjarvis** [comment]
Hi wvangeit, I was installing python 3.6 during a dockerbuild script over the top of an existing python3.4 installation. I am under the impression that python3.6 was only just released so surprised that it can cleanly build bluepyopt. I am also notifying a colleague of this issue. @rgerkin

**Comment by russelljjarvis** [comment]
So the additional lines in my code are:
```

#Install python3.6
RUN wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz
RUN tar xvf Python-3.6.0.tgz
WORKDIR Python-3.6.0
RUN apt-get install -y zlib1g-dev
RUN ./configure --enable-optimizations
RUN make -j8
RUN make altinstall
RUN python3.6
RUN pip install future
RUN pip install --upgrade pip
RUN apt-get install -y python-matplotlib

RUN easy_install gevent
RUN easy_install greenlet


WORKDIR $WORK_HOME
RUN git clone https://github.com/PythonCharmers/python-future
WORKDIR $WORK_HOME/python-future
RUN python3.6 setup.py install

RUN pip install markupsafe


RUN git clone git://github.com/mitsuhiko/jinja2.git
WORKDIR jinja2
RUN python3.6 setup.py install


WORKDIR $WORK_HOME/BluePyOpt

WORKDIR $WORK_HOME
RUN git clone https://github.com/BlueBrain/BluePyOpt
WORKDIR $WORK_HOME/BluePyOpt
RUN python3.6 setup.py install
```

**Comment by russelljjarvis** [comment]
See [here](https://github.com/scidash/docker-stacks/blob/russell_weasel/iceweasel/Dockerfile#L42-L76).

**Comment by russelljjarvis** [comment]
The build fails because it can't find MarkupSafe a jinja2 dependency. python3.6 seems to build jinja2 succesfully and then check that its requirements are satisfied (they are not because of MarkupSafe).
```
Adding Jinja2 2.10.dev0 to easy-install.pth file

Installed /usr/local/lib/python3.6/site-packages/Jinja2-2.10.dev0-py3.6.egg
Processing dependencies for Jinja2==2.10.dev0
Searching for MarkupSafe>=0.23
Reading https://pypi.python.org/simple/MarkupSafe/
Download error on https://pypi.python.org/simple/MarkupSafe/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'MarkupSafe' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for MarkupSafe>=0.23
error: Could not find suitable distribution for Requirement.parse('MarkupSafe>=0.23')
The command '/bin/sh -c python3.6 setup.py install' returned a non-zero code: 1

```

**Comment by russelljjarvis** [comment]
I am also getting the error when I try to build jinja2:
```
fi
Traceback (most recent call last):
  File "/home/jovyan/jNeuroML/Python-3.6.0/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jovyan/jNeuroML/Python-3.6.0/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/jNeuroML/Python-3.6.0/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/home/jovyan/jNeuroML/Python-3.6.0/Lib/ensurepip/__init__.py", line 189, in _main
    default_pip=args.default_pip,
  File "/home/jovyan/jNeuroML/Python-3.6.0/Lib/ensurepip/__init__.py", line 102, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/home/jovyan/jNeuroML/Python-3.6.0/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1074: recipe for target 'altinstall' failed
make: *** [altinstall] Error 1
The command '/bin/sh -c make altinstall' returned a non-zero code: 2
russell@rjjarvis:~/gitpullrequest/iceweasel$ 
```

**Comment by mgeplf** [comment]
For the jinja install, it looks like python36 wasn't built w/ crypto:
`Download error on https://pypi.python.org/simple/: unknown url type: https`
I suspect that could be fixed by adding `libssl-dev`, if the distribution is debian based but that's a guess.

And for the zip error, it looks like installing `zlib1g-dev` isn't enough to make sure python3.6 builds in zip support, or at least it's not picking it up properly.

Could you post the full python3.6 configure and build log?  If I remember correctly, there should be a `checking for inflateCopy in -lz... yes` if it finds zlib.

Alternatively, doing `python3 -c 'import zlib'` should show if zlib is properly installed.

**Comment by rgerkin** [comment]
I think this will be significantly easier when a Python 3.6 version of miniconda is released, perhaps [later this month](https://github.com/ContinuumIO/anaconda-issues/issues/1315).  Then the upstream Docker images can just be patched (in one line) to use the 3.6 flavor of Miniconda, and hopefully the build will be easier from there.

**Comment by russelljjarvis** [comment]
I should point out that `BluePyOpt` `pip` installs okay at this point. My reason for employing the git clone approach is because I also wanted the examples installed. So I have pip installed bluepyopt and I have git cloned the `BluePyOpt` repository containing examples. 

My main reason for being interested in `BluePyOpt` is because I believe perhaps incorrectly that package is able to run parallel `DEAP` with scoop on `NEURON` models, as this is currently something I am trying to achieve, however I have run into a stumbling block: `futures.map` must be able to `pickle` the evaluate function however my evaluate function contains a `NEURON` model (which can't be pickled). Evaluation of the NEURON model is also where most of he computational overhead is, so I don't want to solve the problem in a way that means factoring the `NEURON` simulations outside of the `evaluate` function. The issue is documented [here](https://github.com/russelljjarvis/neuronunit/issues/2).

 @wvangeit, it would be great to get your opinion about whether using the BluePyOpt framework will ultimately allow me parallelize the call to NEURON, and or also if I should be using ipythonparallel instead of scoop?

**Comment by wvangeit** [comment]
hi @russelljjarvis, 
indeed, the pickling of the evaluate function (especially for NEURON models) is a tricky business.
We did solve a lot of these issues in BluePyOpt. But mostly for the case in which the user uses the BluePyOpt ephys submodule to build the model.(https://github.com/BlueBrain/BluePyOpt/tree/master/bluepyopt/ephys)
When you mention your evaluate function. Is this a function that is using the ephys submodule (e.g. does it create e.g. a CellModel object, see the l5pc or simplecell example for more details) ? Or is it a standalone evaluate function (like e.g. the graupnerbrunelstdp bluepyopt example) ?

Regarding scoop/ipyparallel. Both should work, but we have been moving most of our code to ipyparallel. There is some example code inside the l5pc example to use ipyparallel. There are also some shell script to start the ipyparallel engines here: https://github.com/BlueBrain/BluePyOpt/tree/master/examples/l5pc/benchmark
(however the exact way to start the engines will depend on the cluster you are running it on).

**Comment by russelljjarvis** [comment]
Hi again @wvangeit,

I installed ipythonparallel in the docker build, however with a standard install,

`ipcluster` and the python program I am trying to launch both require `sudo` to run. Otherwise executing these commands results in permission denied errrors, however if I do launch these programs with sudo, my `$USER` `$PYTHONPATH` is no longer visible, meaning that the program can't run correctly.

I am interested if you know how to install ipcluster and ipythonparallel such that it does not require sudo permission to run?

**Comment by russelljjarvis** [comment]
I have found a work around to get it to work but its not very elegant or pleasant. I suspect it may be the docker environment that is causing these complications.

For some reason `--profile=default_profile` requires `sudo`
but the command below does not:
` ipcluster start --profile=chase --debug &`
so 1:
`ipcluster start --profile=chase --debug &`
2:
`sudo cp -r /home/jovyan/.ipython/profile_chase/security ~/.ipython/profile_default`
3:
` sudo chown -R jovyan ~/.ipython/profile_default`
Finally 
4:

```
ipython
In [1]: import ipyparallel as ipp

In [2]: rc = ipp.Client()
2017-01-14 21:16:55.760 [IPClusterStart] b'2017-01-14 21:12:54.533 [IPControllerApp] registration::finished registering engine 4:6c417667-4bdf-4093-9544-f24e73ff3b5b'
2017-01-14 21:16:55.760 [IPClusterStart] b'2017-01-14 21:12:54.534 [IPControllerApp] engine::Engine Connected: 4'
2017-01-14 21:16:55.761 [IPClusterStart] b"2017-01-14 21:16:55.759 [IPControllerApp] client::client b'\\x00k\\x8bEh' requested 'connection_request'"

In [3]: rc.ids
Out[3]: [0, 1, 2, 3, 4, 5, 6, 7]
```

**Comment by wvangeit** [comment]
@russelljjarvis Ok, looks good.
Wouldn't it, instead of copying the security directory, make more sense to start the ip client inside the python code using:
rc = Client(profile='chase') ?
Or didn't that work ?

**Comment by russelljjarvis** [comment]
@wvangeit yes thanks this approach works. This is how I have confirmed it from within a docker build:

RUN echo "import os">> run_ipp1.py
RUN echo "os.system('ipcluster start --profile=chase --debug &')" >> run_ipp1.py
```
RUN echo "import ipyparallel as ipp ; rc = ipp.Client(profile='chase'); print('hello from before cpu '); print(rc.ids);" >> run_ipp2.py
ENTRYPOINT cat run_ipp.py && ipython run_ipp1.py && sleep 15 && ipython run_ipp2.py 
```

**Comment by wvangeit** [comment]
Ok, great to hear that works, let me know if there are more issues

**Comment by russelljjarvis** [comment]
Hi @wvangeit 
Actually there are more problems. I am using ipython parallels `v.map_sync` function to map the same evaluate function described above. This seemed to work okay with `futures.map`, however `v.map_sync` does not like my evaluate function again for pickleing related reasons but this time pertaining to the `Individuals deap.creator' attribute.

I am still not implementing any of this with bluepyopts or the ephys frame work. The reason for this is. rgherkin has already implemented a lot of the signal processing and feature extraction code (that I might otherwise use ephys for) in `neuronunit` and `sciunit`, and also I want to use the nsga2 algorithm to efficiently solve a multiobjective multiparameter optimization problem, and thus I have written the standalone evaluate function given above.

However I am starting to come around to using bluepyopt. Especially just the Optimization class specified in the `optimization.py` file. Do you think it should be possible to instantiate this class and use it in combination with my evaluate function but without using the rest of the bluepyopt frame work? Also if I did that, do you think it would help the ipythonparallels problem with pickeling the evaluate function?

Thanks again.
Russell.



```
---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)/opt/conda/lib/python3.5/site-packages/ipyparallel/serialize/serialize.py in unpack_apply_message(bufs, g, copy)
    192     args = []
    193     for i in range(info['nargs']):
--> 194         arg, arg_bufs = deserialize_object(arg_bufs, g)
    195         args.append(arg)
    196     args = tuple(args)
/opt/conda/lib/python3.5/site-packages/ipyparallel/serialize/serialize.py in deserialize_object(buffers, g)
    130     bufs = list(buffers)
    131     pobj = buffer_to_bytes_py2(bufs.pop(0))
--> 132     canned = pickle.loads(pobj)
    133     if istype(canned, sequence_types) and len(canned) < MAX_ITEMS:
    134         for c in canned:
AttributeError: Can't get attribute 'Individual' on <module 'deap.creator' from '/opt/conda/lib/python3.5/site-packages/deap/creator.py'>

... 12 more exceptions ...
```

**Comment by wvangeit** [comment]
Hi, 
Yes this is one of the typical problems we worked to solve in BluePyOpt.
You probably should indeed use the Optimisation class with your evaluator. An example on how to interface with an 'external' evaluator can be found here:
https://github.com/BlueBrain/BluePyOpt/tree/master/examples/graupnerbrunelstdp

Is there any specific reason you want to use NSGA2 over the IBEA algorithm implemented in BluePyOpt. In my experience IBEA mostly outperforms NSGA2. But if you need to I can provide you with a line of code that would switch BluePyOpt to use NSGA2 instead of IBEA.

**Comment by russelljjarvis** [comment]
Hi Wvangeit, yes I would love it if you could provide the line of code to switch algorithms. That would be great. I am still working on this issue. 

As well as opting out of using `ephys` for feature extraction and DSP. Do you think I can also opt out of using BluePyOpts way of declaring and expressing the parameters to be optimized. 

For example I just want to use routines similar to the one below:
Where everything that is appended to the list rov is parameter range.

Some of these parameters might only exist in the py-hoc space, as opposed to NMODL. I might actually try to use BluePyOpts way of specifying parameters, I just remember struggling with this for a long time previous (however this was a year ago, so the code may have changed significantly since then).

Regardless I am getting some unrelated errors that I could share with you. Thanks again for your help. Russell.


```
NDIM= 10
rov=[]
vr = np.linspace(-75,-45,1000)
a = np.linspace(0.015,0.045,1000)
b = np.linspace(-0.0010,-0.0035,1000)
k = np.linspace(7.0E-4-+7.0E-5,7.0E-4+70E-5,1000)
c = np.linspace(-50.0-10.0,-50+10,1000)
C = np.linspace(1.00000005E-4-1.00000005E-5,1.00000005E-4+1.00000005E-5,1000)
d = np.linspace(0.050,0.2,1000)
v0 = np.linspace(-75,-45,1000)
vt =  np.linspace(-50,-30,1000)
vpeak = np.linspace(25,40,1000)
param=['vr','a','b','C','c','d','v0','k','vt','vpeak']

rov.append(a)
rov.append(b)
rov.append(c)
rov.append(C)
rov.append(d)
rov.append(k)
rov.append(vr)
rov.append(v0)
rov.append(vt)
rov.append(vpeak)

BOUND_LOW=[ np.min(i) for i in rov ]
BOUND_UP=[ np.max(i) for i in rov ]
NDIM = len(rov)


def evaluate(individual):#This method must be pickle-able for scoop to work.
    for i, p in enumerate(param):
        name_value=str(individual[i])
        #reformate values.
        model.name=name_value
        if i==0:
            attrs={'//izhikevich2007Cell':{p:name_value }}
        else:
            attrs['//izhikevich2007Cell'][p]=name_value

    individual.attrs=attrs
    b4nrncall=time.time()
    model.update_run_params(attrs)
    afternrncall=time.time()
    LOCAL_RESULTS.append(afternrncall-b4nrncall)
    individual.params=[]
    for i in attrs['//izhikevich2007Cell'].values():
        if hasattr(individual,'params'):
            individual.params.append(i)

    individual.results=model.results
    score = get_neab.suite.judge(model)
    import numpy as np
    individual.error = [ np.abs(i.score) for i in score.unstack() ]
    individual.s_html=score.to_html()
    error=individual.error
    assert individual.results
    return error[0],error[1],error[2],error[3],error[4],error[5],error[6],error[7],
```

**Comment by wvangeit** [comment]
@russelljjarvis Already regarding your question about NSGA2. I just added a new option to the DEAPOptimisation class, to allow you to specify the selector. The option is 'selector_name'. For now it can be 'IBEA' or 'NSGA2', see here for the doc: http://bluepyopt.readthedocs.io/en/latest/deapext/bluepyopt.deapext.optimisations.html

**Comment by wvangeit** [comment]
Regarding your question about dropping the BluePyOpt parameter declaration. I'm not completely understand what you mean. 
Do you mean the way parameters are specified in the ephys submodule ? Because yes, in the ephys module there are some restrictions. But there also exists the Parameter class outside of ephys: https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/parameters.py. This class is fairly liberal, and doesn't make any assumption about the simulator (or NMODL, pyneuron, etc.). If you use this in combination with an Evaluator (outside of ephys), it should fit most use cases. If it doesn't for you, could you explain in more detail what exactly doesn't work ?
Python also would allow you to override / extend this Parameter class to fit your needs.
