### ISSUE TITLE
Add ability to kill neuron simulation after certain amount of time

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyOpt#214]
Sometimes certian individuals in the population take a long time to evaluate.
It's necessary to provide a mechanism to kill this individuals prematurely, and possible return a bad error score.
At least two mechanisms for this should be implemented:
- based on absolute walltime (disadvantage: walltime can e.g. depend on the compute resources)
- based on slowest in a population, e.g. kill all individuals that take longer than 80% of the population. (disadvantage: requires sending a signal from the object that knows about the population all the way down to the evaluator/simulator.)

**Comment by wvangeit** [comment]
With 'multicore', do you mean when you use ipyparallel ? (or just the python 'multiprocessing' module)

**Comment by anirban6908** [comment]
Yes I meant ipyparallel.

**Comment by wvangeit** [comment]
Do you know if isolate=True was enabled in both of your test cases. I would expect these signal to stay local to an ipyparallel node, but it depends a bit on which machine the 
```
# Change the behavior of SIGALRM
signal.signal(signal.SIGALRM, timeout_handler)
```
gets executed I guess.

An trick/hack I used in the old OptimizerFramework was to create a file on disk that the slaves were monitoring, when they saw the file they stopped. But that was rather used for the option of having the master tell the slaves to stop when 80% of all individuals were evaluated.

**Comment by anirban6908** [comment]
Sorry @wvangeit , I totally missed this. Yes, isolate = True is enabled since it was None in both cases  in protocols.py 

```
if isolate is None:
   isolate = True
```
I see what you are saying, I mean the signal staying local and not affecting the other processors. 

Could you send me the code for the previous hack? Is there an obvious problem implementing that in this case?
Thanks

**Comment by wvangeit** [comment]
I wonder what happens if you put the 
```
signal.signal(signal.SIGALRM, timeout_handler)
```
inside the evaluate_with_dicts method ?

The old hack is in C++ and written for completely different software, so it won't be much of help here. The idea is to let the master process (before the call to the map function) to create a file with some content. The slaves (after the map process) read the file from time to time, when the file changes or disappears (whatever the master does when more than e.g. 80% of the soutions have been evaluated) they stop evaluating. I assume this 'could' be implemented using a wrapper around the map function provided to the optimizer.

**Comment by anirban6908** [comment]
Were you able to log custom messages from individual engines? I have been trying to log debug/error statements as to understand whether the alarm exception is kicking in but unable to log these messages in the logfiles. I looked up online and used this

```
from IPython.config import Application
logger = Application.instance().log
```
but no result.

**Comment by wvangeit** [comment]
@DrTaDa, I assume this is implemented?

**Comment by DrTaDa** [comment]
@wvangeit the "absolute walltime" is implement: the user needs to specify a timeout in second per protocol (if the optimisation uses N protocols, the final run time for a pathological parameter set will be N*timeout). When this timeout is reached, the computation is killed. If the user does not provide anything or provides None, no timeout is used. 

Do you think dynamic timeout based on the slowest in a population is also needed ?

**Comment by wvangeit** [comment]
I think we can leave it as is for now. Thanks.
