### ISSUE TITLE
Autogenerate package.json

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyOpt#226]
There is at the moment a hardcoded internal BBP related file in the repo: 'package.json'.
This file should be automatically generated.
Related to: 
https://github.com/BlueBrain/BluePyOpt/pull/225

**Comment by tapaswenipathak** [comment]
Reading the [file](https://github.com/BlueBrain/BluePyOpt/blob/master/package.json), what all fields are updatable? Seems like [this](https://github.com/BlueBrain/BluePyOpt/pull/225/files) was added just for documentation purpose, if very few fields could change, I will create a `.sh` file having the options which would update and generate this file.

**Comment by tapaswenipathak** [comment]
@wvangeit gentle re-ping in case you missed this ping.

**Comment by tapaswenipathak** [comment]
@wvangeit gentle reminder in case you missed this ping.

**Comment by wvangeit** [comment]
Closed in favor of #320
