### ISSUE TITLE
Tutorial / Wiki / Guide

### ISSUE THREAD

**Issue by SvennoNito** [BlueBrain/BluePyOpt#231]
Hey again,
I wanted to ask whether you can recommend any sort of documentation, tutorial or guide for BluePyOpt? I went through your simple cell example and now I wonder where I can find ressources if I want to adapt the code to my needs. I wanted to start understanding `bpop.optimisations.DEAPOptimisation()` for example but the only [wiki](http://bluepyopt.readthedocs.io/en/latest/optimisations/bluepyopt.optimisations.html) I found was pretty empty.

**Comment by wvangeit** [comment]
Hi,
Did you already have a look at:
https://github.com/BlueBrain/BluePyOpt/blob/master/examples/l5pc/L5PC.ipynb

This is a fairly complex example that covers quite a lot of the code.

**Comment by wvangeit** [comment]
Will close this for now, let us know if you need more help
