### ISSUE TITLE
scidash branch of BluePyOpt

### ISSUE THREAD

**Issue by russelljjarvis** [BlueBrain/BluePyOpt#247]
I have created a fork of bluepyopt, that is designed to work with dask distributed instead of scoop. Also it uses model parameter dictionaries that get mapped from GA genes. It also uses error functions objective functions that are created by interfacing with neuronunit. 

Since these changes, are not necessarily helpful for general use cases of BluePyOpt, I have discussed how to best integrate these changes with a colleague, and we decided to propose making a sciunit branch of BluePyOpt.

The main places where code is substantially different are:
https://github.com/russelljjarvis/BluePyOpt/blob/scidash/bluepyopt/deapext/optimisations.py#L101-#L144

and:

https://github.com/russelljjarvis/BluePyOpt/blob/scidash/bluepyopt/deapext/optimisations.py#L218-#L231

@rgerkin

**Comment by wvangeit** [comment]
Great to hear that you're extending BluePyOpt.

I had a bit of a look at your changes. Do you think it might be possible to put your changes in new classes (e.g. a subclass of DEAPOptimisation ?). If that would be the case, we probably could merge your changes into the master. If you use some class inheritance we could avoid duplicating a lot of code in your classes.

Maintaining a fork always has the problem that after a while there might be quite some divergence from the master branch, and it would become more and more difficult to merge fixes into the branch.

Let us know what you think about that.

**Comment by russelljjarvis** [comment]
Hi Wvangeit,

Yes thats a great idea to subclass DEAPOptimisation class. I will start working on that over the next few weeks. I think the approach you describe is best.

**Comment by wvangeit** [comment]
@russelljjarvis is there any update about this ?

**Comment by russelljjarvis** [comment]
I  differenced the file 

https://github.com/russelljjarvis/BluePyOpt/blob/elitism/bluepyopt/deapext/optimisations.py

with the original file : https://github.com/russelljjarvis/BluePyOpt/elitism/bluepyopt/deapext/optimisations.py

I found that even though the overall pattern was the same, all but two methods had substantially different code to the original DEAPOptimisation object methods, making the tasl pf refactoring to inherit from `DEAPOptimisation` difficult and less useful.

So instead of using inheritance to make a new class:

`class SciunitOpt(DEAPOptimisation)`

I have just renamed the existing class and inherited from the more fundamental `bluepyopt.optimisations.Optimisation`, which seemed to make more sense.

So now I have: `class SciunitOpt(bluepyopt.optimisations.Optimisation)`

**Comment by wvangeit** [comment]
Thanks for the info @russelljjarvis 
So if I understand it correctly, technically speaking the scidash branch could be merge into the BluePyOpt master (now that your class is inheriting from Optimisation directly).
Would it be ok for you if we merge the SciunitOpt class in the official repo master ?

**Comment by rgerkin** [comment]
@russelljjarvis @wvangeit Would it be OK if we delayed this merge until we are confident that the content is robust across many use cases?

**Comment by russelljjarvis** [comment]
Yes, I am support of @rgerkin above stated idea about delaying pending robustness tests. The registration of the intention to merge still stands.

**Comment by wvangeit** [comment]
@russelljjarvis @rgerkin sure, I'm ok with delaying it. (To avoid making the merge more difficult, I'll try to ping you if anybody would make changes to Optimisation/DEAPOptimisation in the future.)

**Comment by wvangeit** [comment]
@russelljjarvis sorry, not sure I completely understand. What do you mean with 'the model seems to be able to sense' ? Do you mean that certain parameter sets run much faster? This might be caused by the variable timestep method of Neuron.

**Comment by rgerkin** [comment]
@wvangeit I think he means variable timestep.  @russelljjarvis Do you remember [this](https://www.neuron.yale.edu/neuron/static/py_doc/simctrl/cvode.html#CVode.active) command which can turn that variable timestep on and off?  If it is on (possibly be default) it will skip over the "boring" parts of the simulation with a big jumps.  If you turn it off, it should respect your dt.

**Comment by wvangeit** [comment]
Ok, but so I'd suggest to leave the variable timestep on during non-spiking traces, it will significantly decrease the simulation time (and normally have no negative effects)

**Comment by russelljjarvis** [comment]
Yes I did mean variable timestep and NEURON cvode. I guess, what I need is a method to interpolated fixed times, given a changing time step signal. That code probably exists in a lot of different places.

Also @wvangeit  on the L5PC model, I wonder if you know how I can find out where the data lives that was used to constrain that model?

I suspect it might be one of these data sets, but they are all unlabelled so it is impossible to tell.
http://microcircuits.epfl.ch/#/article/article_4_eph
