### ISSUE TITLE
Synaptic Weight optimization

### ISSUE THREAD

**Issue by alexandrapierri** [BlueBrain/BluePyOpt#249]
Hello 

Is Bluepyopt suitable for optimization of synaptic weights?
Are there any such examples?

Thank you

**Comment by wvangeit** [comment]
Sure, we never tried it, but it should be possible.
Which simulator are you using ?
If it's NEURON you can use, you should be able to use the NrnPointProcessParameter like in this example to set the weight of the netcon or the conductance of the synapse file:
https://github.com/BlueBrain/BluePyOpt/blob/master/examples/expsyn/ExpSyn.ipynb
In case you're using another simulator, there is always the option of creating your own evaluator, like in:
https://github.com/BlueBrain/BluePyOpt/tree/master/examples/graupnerbrunelstdp

Let me know if you need more help

**Comment by alexandrapierri** [comment]
thank you Werner 

my objective is to optimize synaptic weights of my cell models using NEURON. 
I want to find that parameter space of synaptic weights that allows my cells to exhibit specifc firing patterns. 

thanks for your advice, 
Alexandra
________________________________________

**Comment by wvangeit** [comment]
Will close this for now, let us know if you need more help
