### ISSUE TITLE
OSError: Morphology not found at 'simple.swc'

### ISSUE THREAD

**Issue by alexandrapierri** [BlueBrain/BluePyOpt#250]
hello 

When I execute on jupyter the following lines for the simplecell.ipynb example:

default_params = {'gnabar_hh': 0.1, 'gkbar_hh': 0.03}
responses = twostep_protocol.run(cell_model=simple_cell, param_values=default_params, sim=nrn)

the following error appears. I use Python 3.6 the Anaconda release on Windows. 
Thanks for any help/suggestions. 

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\protocols.py", line 155, in _run_func
    cell_model.instantiate(sim=sim)
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\models.py", line 222, in instantiate
    self.morphology.instantiate(sim=sim, icell=self.icell)
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\morphologies.py", line 91, in instantiate
    self.morphology_path)
OSError: Morphology not found at 'simple.swc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alexandra\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\protocols.py", line 185, in _run_func
    traceback.format_exception(*sys.exc_info())))
Exception: Traceback (most recent call last):
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\protocols.py", line 155, in _run_func
    cell_model.instantiate(sim=sim)
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\models.py", line 222, in instantiate
    self.morphology.instantiate(sim=sim, icell=self.icell)
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\morphologies.py", line 91, in instantiate
    self.morphology_path)
OSError: Morphology not found at 'simple.swc'

"""

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-34-b41867be1955> in <module>()
      1 default_params = {'gnabar_hh': 0.1, 'gkbar_hh': 0.03}
----> 2 responses = twostep_protocol.run(cell_model=simple_cell, param_values=default_params, sim=nrn)

~\Anaconda3\lib\site-packages\bluepyopt\ephys\protocols.py in run(self, cell_model, param_values, sim, isolate)
     71                 param_values=param_values,
     72                 sim=sim,
---> 73                 isolate=isolate)
     74 
     75             key_intersect = set(

~\Anaconda3\lib\site-packages\bluepyopt\ephys\protocols.py in run(self, cell_model, param_values, sim, isolate)
    208                     'cell_model': cell_model,
    209                     'param_values': param_values,
--> 210                     'sim': sim})
    211 
    212             pool.terminate()

~\Anaconda3\lib\multiprocessing\pool.py in apply(self, func, args, kwds)
    257         '''
    258         assert self._state == RUN
--> 259         return self.apply_async(func, args, kwds).get()
    260 
    261     def map(self, func, iterable, chunksize=None):

~\Anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

Exception: Traceback (most recent call last):
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\protocols.py", line 155, in _run_func
    cell_model.instantiate(sim=sim)
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\models.py", line 222, in instantiate
    self.morphology.instantiate(sim=sim, icell=self.icell)
  File "C:\Users\Alexandra\Anaconda3\lib\site-packages\bluepyopt\ephys\morphologies.py", line 91, in instantiate
    self.morphology_path)
OSError: Morphology not found at 'simple.swc'

**Comment by wvangeit** [comment]
If you're learning how to use bluepyopt, another useful link might be:
https://www.edx.org/course/simulation-neuroscience-epflx-simneurox
Among other things this MOOC explains you how to use BluePyOpt, and how to run it online using the HBP Collaboratory

**Comment by alexandrapierri** [comment]
hello Werner 

thank you for these links as well as your previous e-mails. 
As mentioned before my objective is to optimize synaptic weights on my cell models using NEURON. 
Do you think Bluepyopt is the appropriate tool to use for this endeavor or are there other more appropriate optimization tools for this by the BlueBrain project?

thank you, 
Alexandra
________________________________________

**Comment by wvangeit** [comment]
I would say to at least try with BluePyOpt and see how it goes, normally it should be able to handle this.
What exactly is your fitness function ?

**Comment by wvangeit** [comment]
I will close this for now, let me know if you need more help

**Comment by alexandrapierri** [comment]
As a fitness function I want to use the spiking activity of the cell. My code is in hoc and I want to optimize a certain parameter of the model (synaptic weights) already written in hoc. Would it be the right approach to import the hoc code in the bluepyopt python script as part of the morphology code and only re-write/define in python the part of the code that needs to be optimized? Namely I was thinking to import my hoc code with every model detail (ion channels etc) under morph = ephys.morphologies.NrnFileMorphology('mymodel.swc') and only rewrite in python (and remove from hoc) the portion that needs to be optimized, would you agree with that logic?

**Comment by alexandrapierri** [comment]
thanks Werner
________________________________________

**Comment by alexandrapierri** [comment]
Hi again. In terms of the cell morphology that I need to import can I use a hoc file containing my model? I do not have an swc file and using my hoc file pops me error: ValueError: Unknown filetype: hoc. Thanks!

**Comment by wvangeit** [comment]
There was a similar question in this issue: https://github.com/BlueBrain/BluePyOpt/issues/253
The solution was to convert the HOC morphology to SWC (this won't necessarily work for all HOC morphs though). Should we try that ?

**Comment by alexandrapierri** [comment]
yes let's try it. Should I e-mail you an example of my morphologies? My e-mail is: alex4@windowslive.com
