### ISSUE TITLE
Optimizing channel models

### ISSUE THREAD

**Issue by rgerkin** [BlueBrain/BluePyOpt#255]
@gsarma and I are working on optimization of ion channel models [here](https://github.com/openworm/ChannelWorm2) for the Open Worm project, and are interested in using BluePyOpt.  We reviewed your example with the HH neuron, but were wondering how we might handle an objective function constructed around channel recordings (e.g. peak and steady-state current during measurement of an IV curve).  One option would be to create these objectives by hand, but are there any objective functions for this sort of purpose that are already being used with BluePyOpt, possibly for ion channel model optimizations as part of HBP?  More generally, do you have any example scripts/notebooks doing ion channel model optimization?

**Comment by wvangeit** [comment]
Hi @rgerkin 
Unfortunately I'm not aware of anybody using BluePyOpt for ion channel optimization. So I'm afraid you would have to implement something yourself. If you have something, we're always happy to incorporate it into the master.

**Comment by wvangeit** [comment]
@rgerkin, is there anything else I could help with, or can we close this ticket ?

**Comment by rgerkin** [comment]
@wvangeit No, thank you.
