### ISSUE TITLE
manage the value of several 'sub'Parameter objects at the same time

### ISSUE THREAD

**Issue by clupascu** [BlueBrain/BluePyOpt#260]
Add a new subclass of Parameter, that would manage the value of several 'sub'Parameter objects at the same time.

Same global variable in the Neuron block in two or more mod files should have same values at the end of optimization.

At the moment variable alpha in the Neuron block of one mod file is defined as

NEURON {
        SUFFIX    kmdb
        GLOBAL inf, tau,alpha
}

while in one other mod file alpha is defined as

NEURON {
        SUFFIX kdr
        GLOBAL ninf,taun,zetan,vhalfn,vhalfn2,zetan2,alpha
}

When we refer to the variable in the parameters.json for the optimization we refer to it as alpha_kmdb in the first case and alpha_kdr in the second case.

The two mod files are present in different sections in the morphology. Let's say one in the axonal and one in the somatic.

We would like to have the same value for all the alpha variables in the different mod files.

If we write in the json something like this

"optimized": {
        "all": [
       ],
        "axonal": [
           ["alpha_kmdb", 0.025, 0.15, "uniform" ]
       ],
       "somatic": [
           ["alpha_kdr", 0.025, 0.15, "uniform" ]
       ]

the two values will have different values at the end of the optimization.

**Comment by wvangeit** [comment]
This was implemented here:
https://github.com/BlueBrain/BluePyOpt/pull/262

It was merged into the master. It will be pushed to pypi in the next 10 minutes or so. When you upgrade bluepyopt to a version >= 1.7 it will contain the feature.

I've add an ipython notebook that shows how to use the new functionality:
https://github.com/BlueBrain/BluePyOpt/tree/master/examples/metaparameters

**Comment by clupascu** [comment]
Thank you @wvangeit. I will test it and let you know.
