### ISSUE TITLE
Including tests + licenses in release tars

### ISSUE THREAD

**Issue by sanjayankur31** [BlueBrain/BluePyOpt#280]
Hi,

Would it be possible to please include tests and the license files in the release tars? At the moment, they are not included in the pypi release downloads.

Alternatively, if these are deemed unnecessary for the pypi tar, could the tags/releases on github please match the pypi releases so that downstream maintainers can use the sources from here?

It is currently in review for inclusion in [NeuroFedora](https://neuro.fedoraproject.org), where these issues cropped up: https://bugzilla.redhat.com/show_bug.cgi?id=1727505

**Comment by wvangeit** [comment]
I'm changing the manifest here:
https://github.com/BlueBrain/BluePyOpt/pull/281

It will include the license files etc, and also the bluepyopt/tests directory

**Comment by wvangeit** [comment]
PR was merged

**Comment by sanjayankur31** [comment]
Thanks very much! Could github tags/releases also be kept in sync with Pypi? It just makes it a little easier to go through the commit tree to figure out changes.

**Comment by wvangeit** [comment]
Aren't they in sync with pypi ? E.g. the latest tag is 1.8 (which is also the latest major pypi version)
The patch version number is number of commits since the major version

**Comment by sanjayankur31** [comment]
Ah, right! We didn't realise that each patch version corresponded to a commit. 

This brings up an additional question then: are users/downstreams expected to update their installation with each patch release? Or is it OK if we stick to major.minor releases only? One could run `pip update` every day, but we can't do that in downstream distributions where we want go give the build enough time so it can go through the QA process.

**Comment by wvangeit** [comment]
It should be to follow the major.minor release. The patch release are in general fairly unimportant updates.
