### ISSUE TITLE
Python 3 requires explicit flag to open pickle binary files

### ISSUE THREAD

**Issue by pineider** [BlueBrain/BluePyOpt#290]
Resuming from a checkpoint fails in Python 3 because of a missing "b" flag in pickle load.

**Comment by wvangeit** [comment]
@DrTaDa could you have a look, is this still a problem?

**Comment by DrTaDa** [comment]
@wvangeit I couldn't reproduce this issue and there is a "b" flag in both the reading and writing of the pickle. Maybe @pineider you accidentally tried to open a python2 pickle in python3 ?

**Comment by pineider** [comment]
Hello,

I added the missing "b" and we merged the pull request a long time ago.
The bug report should have been closed.

Cheers
