### ISSUE TITLE
ephys.create_hoc

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/BluePyOpt#297]
Hi!
Considering that `ephys.create_hoc.create_hoc` allows to specify a custom template via `template_filename` and `template_dir`, it would be really great to allow additional custom arguments for rendering. For example my custom template would be the same as [cell_template.jinja2](https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/templates/cell_template.jinja2) but with custom `geom_nseg` that requires `my_custom_number` param:
```
// the same as `cell_template.jinja2`
...
proc geom_nseg() {
  this.geom_nseg_fixed({{my_custom_number}})
}
...
// the same as `cell_template.jinja2`
```
Then one can use the custom template easily with:
```
ephys.create_hoc.create_hoc(..., my_custom_number=13)
```
Also can we replace `template_dir` and `template_filename` with `template_filepath`? It would reduce the number of args but won't change functionality.

**Comment by wvangeit** [comment]
I'd propose we add an argument that accepts a dict with arguments to the jinja template.

About template_filepath, don't think that's a good idea. Don't see that much advantage, but the disadvantage is that it would break backward compatibility

**Comment by asanin-epfl** [comment]
Closing in favor of #298
