### ISSUE TITLE
Difference between calculating the features using efel versus when using fitcalc.calculate_scores

### ISSUE THREAD

**Issue by orena1** [BlueBrain/BluePyOpt#303]
Hi I am comparing the results of the efel vs fitcalc.calculate_scores and it seems that there is a difference.

```python
scores = fitcalc.calculate_scores(best_responses)


import efel
import pandas as pd
trace1 = {'T': best_responses['IDRest_7.soma.v'].response['time'], 'V':best_responses['IDRest_7.soma.v'].response['voltage']}
trace1['stim_start'] = [700]
trace1['stim_end'] = [2700]
traces_results = efel.getFeatureValues([trace1],
                                ['AP_height','AP_amplitude','Spikecount','AHP_depth_abs'])


traces_results


print('IDRest_7_AHP_depth_abs')
print('manual calculation - ' + str((-69.4687143541 - traces_results[0]['AHP_depth_abs'].mean())/0.539758874442))
print('bluepyopt calculation - ' + str(scores['IDRest_7.soma.AHP_depth_abs']))
```

IIDRest_7_AHP_depth_abs
manual calculation : 29.24285168089122
bluepyopt calculation : 36.269754996091436

See full example in the attached zip -[Show_Bug.zip](https://github.com/BlueBrain/BluePyOpt/files/4450885/Show_Bug.zip) -  file, open Show_error.ipynb for full details,
Thanks.

Might be related to https://github.com/BlueBrain/eFEL/issues/166

**Comment by wvangeit** [comment]
@DrTaDa , could you have a look?

**Comment by wvangeit** [comment]
(I'd try to manually see what efel.getDistance() returns for this trace / values)

**Comment by DrTaDa** [comment]
Hello @orena1, 
The discrepancy you see does not come from BluePyOpt but from the way the score is computed in eFel.

As you can see from https://github.com/BlueBrain/eFEL/blob/master/efel/api.py, line 230, scores are computed as:
```
for feature_value in feature_values:
    distance += abs(feature_value - meann)
distance = distance / stdd / len(feature_values)
```
In your by hand computation, you do:
`abs(-69.4687143541 - score1[0]['AHP_depth_abs'].mean())/0.539758874442`
To compare with eFel, it should be:
`abs(-69.4687143541 - score1[0]['AHP_depth_abs']).mean()/0.539758874442`

**Comment by orena1** [comment]
Got it, thanks!
