### ISSUE TITLE
'Not disabling banner' error

### ISSUE THREAD

**Issue by strawcup** [BlueBrain/BluePyOpt#306]
Hi, 

I get the following error after I run nrn = ephys.simulators.NrNSimulator() in simplecell.ipynb:

/Users/jyang/opt/anaconda3/lib/python3.7/site-packages/bluepyopt/ephys/simulators.py:75: UserWarning: Unable to find Neuron hoc shared library in /Applications/NEURON-7.7/nrn/lib/python/neuron, not disabling banner
'not disabling banner' % nrnpy_path)

Any ideas why I'm getting this error? Thanks in advance.

**Comment by wvangeit** [comment]
For the record, I also answered in gitter. 
"Does this stop the execution? It's a warning and normally shouldn't affect the execution itself."

**Comment by strawcup** [comment]
Thanks for the response. Just re-posting my response on gitter:

You're right-- it doesn't stop the execution itself, but I get a timeout error when I run the next line 'responses = twostep_protocol.run(cell_model=simple_cell, param_values=default_params, sim=nrn)':

ProcessExpired Traceback (most recent call last)

<ipython-input-16-b41867be1955> in <module>
1 default_params = {'gnabar_hh': 0.1, 'gkbar_hh': 0.03}
----> 2 responses = twostep_protocol.run(cell_model=simple_cell, param_values=default_params, sim=nrn)

~/opt/anaconda3/lib/python3.7/site-packages/bluepyopt/ephys/protocols.py in run(self, cell_model, param_values, sim, isolate, timeout)
81 sim=sim,
82 isolate=isolate,
---> 83 timeout=timeout)
84 except TypeError as e:
85 if "unexpected keyword" in str(e):

~/opt/anaconda3/lib/python3.7/site-packages/bluepyopt/ephys/protocols.py in run(self, cell_model, param_values, sim, isolate, timeout)
233 timeout=timeout)
234 try:
--> 235 responses = tasks.result()
236 except TimeoutError:
237 logger.debug('SweepProtocol: task took longer than '

~/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
433 raise CancelledError()
434 elif self._state == FINISHED:
--> 435 return self.__get_result()
436 else:
437 raise TimeoutError()

~/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py in get_result(self)
382 def get_result(self):
383 if self._exception:
--> 384 raise self._exception
385 else:
386 return self._result

ProcessExpired: Abnormal termination

**Comment by wvangeit** [comment]
So based on "SweepProtocol: task took longer than " it looks like your protocol took longer than the timeout value. Did you manually set a value for the timeout?

Apart from that, it seems something goes wrong in the error handling when the timeout is reached.
@DrTaDa, do you know where this "if "unexpected keyword" in str(e):" comes from?

**Comment by DrTaDa** [comment]
@wvangeit I added that because some users where overloading the protocol.run function before the timeout merge and thus their run function couldn't take timeout as an argument (eg: https://github.com/BlueBrain/BluePyOpt/blob/e6b6c44daefe1a2a4e0444ec392e427f45a07b1b/examples/thalamocortical-cell/CellEvalSetup/protocols.py#L64)

**Comment by wvangeit** [comment]
Mmm, but so then what could be causing the issue above?

**Comment by strawcup** [comment]
@wvangeit No, I did not manually set a value for the timeout. I haven't changed anything in the simplecell example...

**Comment by DrTaDa** [comment]
Hello @strawcup, 
if you are on MacOs, can you try downgrading your pebble version to 4.3.10 (pip install pebble==4.3.10) ?

**Comment by strawcup** [comment]
@DrTaDa thank you!! It's working now. I will close this issue.

**Comment by strawcup** [comment]
I have another question unrelated to the error--

I am trying to optimize for current threshold (i.e. rheobase) and was wondering if there is a built-in function that I could use. Thanks very much for your help!

**Comment by wvangeit** [comment]
No sorry, there is no built-in function that can do that. I assume you should be able to create something using the Spikecount feature of eFEL.
