### ISSUE TITLE
no_banner_ seems not working with python 3.7

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/BluePyOpt#314]
I get some warnings like:

`Warning: no DISPLAY environment variable.`
`--No graphics will be displayed.`

with python3.7, which I can reproduce by `from neuron import gui`, so it is related to the banner/gui of neuron. It should be disabled by https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/simulators.py#L65, but it seems to not be the case.

**Comment by wvangeit** [comment]
I don't think the nrn_disable_banner option will disable this warning. That option is meant to disable the full neuron banner.
How did you install neuron? If you want to get rid of this, the best way might be to use a NEURON that doesn't have X11 compiled into it.

**Comment by arnaudon** [comment]
I use the new `pip install NEURON`, so that must be it then... thanks!

**Comment by wvangeit** [comment]
Are you getting this message for every single evaluation?
Maybe we should ask in the neuron issues to also provide a wheel for neuron without x?
