### ISSUE TITLE
Example in Quick Start needs to be updated

### ISSUE THREAD

**Issue by sunzhenyang2018** [BlueBrain/BluePyOpt#316]
I was following alone the optimization set up in the jupyter notebook in Quick Start, and this happened

![opt_issue1](https://user-images.githubusercontent.com/65326026/90075418-30d86980-dcb2-11ea-9a95-18ce38416c71.JPG)

Either DEAPOptimization is deprecated or the example has a typo.

**Comment by DrTaDa** [comment]
Dear @sunzhenyang2018, 
The name of the class is indeed DEAPOptimisation with an "s". I was not able to find a typo in the example notebook, if there is, could you give us the line number ?

**Comment by DrTaDa** [comment]
Dear @sunzhenyang2018,
The name of the class is indeed DEAPOptimisation with an "s". I was not able to find a typo in the example notebook, if there is, could you give us the line number ?

**Comment by wvangeit** [comment]
@sunzhenyang2018 I will close this. I assume the 'z' was the problem?

**Comment by sunzhenyang2018** [comment]
Yes, sorry about that. I made a typo there.
