### ISSUE TITLE
Update on IP information

### ISSUE THREAD

**Issue by ASVG** [BlueBrain/BluePyOpt#317]
Following up on the discussion with Werner, I am creating this ticket for changes.

1. Copyright: Please update the information on copyright. (c) 2016-2020, Blue Brain Project/ EPFL. The last year (2020) should be updated each new year. Please make it consistent where it appears.

2. Authors: Currently Giuseppe, JDC, Mike, Christian, and Werner are listed as authors. Please update it to reflect the current status. (<- Tanguy!)

Thank you.

**Comment by wvangeit** [comment]
This was fixed by https://github.com/BlueBrain/BluePyOpt/pull/318

**Comment by wvangeit** [comment]
(changed files are here:https://github.com/BlueBrain/BluePyOpt/pull/318/files)
