### ISSUE TITLE
IPython and Map_function

### ISSUE THREAD

**Issue by FrancescoCavarretta** [BlueBrain/BluePyOpt#319]
I would like to run in parallel the BluePyOpt using ipyparallel.
To instantiate an **bluepyopt.optimisations.DEAPOptimisation** object in ipyparallel, 
do I need to set a new **map_function** that differ from the built-in **map**?

In case, what kind of parallel **map** object do you suggest to use?

**Comment by wvangeit** [comment]
Yes, indeed.
Here are some examples on how to use ipyparallel:
start.sh in https://github.com/BlueBrain/BluePyOpt/tree/master/examples/l5pc/benchmark
and https://github.com/BlueBrain/BluePyOpt/blob/master/examples/l5pc/opt_l5pc.py
