### ISSUE TITLE
Make checkpointing safer

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyOpt#323]
As mentioned by @Aman-A on gitter, there is a possibility of the checkpoint disappearing if (probably) something goes wrong during the write of the checkpoint. This loses all history of the optimization. We should make this a bit safer.

One option see is doing the following:
- first write checkpoint to temporary file (just same name with extra .tmp extension?)
- issue a copy command from tmp -> main file
- leave the .tmp file there until the next generation

This way there are always two copies around, and the copy command is mostly more atomic.

**Comment by DrTaDa** [comment]
I agree, that's a needed feature. I happens often with slurm that the time limit is reached during the writing of the pickle file, corrupting it.

**Comment by wvangeit** [comment]
@DrTaDa so can this be closed based on your fix?

**Comment by DrTaDa** [comment]
Yes !
