### ISSUE TITLE
Question about `nseg` variable in `geom_nsec` function of cell_template.jinja2

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/BluePyOpt#339]
This var `nseg` seems undefined. How is it set?
https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/templates/cell_template.jinja2#L197

**Comment by wvangeit** [comment]
nseg is a variable that's automatically defined by neuron for each section.

**Comment by asanin-epfl** [comment]
thank you!
