### ISSUE TITLE
RFE: Move away from using deprecated nose for testing

### ISSUE THREAD

**Issue by sanjayankur31** [BlueBrain/BluePyOpt#358]
# Feature
nose is deprecated, so it'll be good to move to another testing tool, perhaps py.test.

# Motivation
nose is deprecated upstream (the last commit was in 2016.) and is also being deprecated in Fedora.

https://github.com/nose-devs/nose/commits/master

It is still in use here, though

https://github.com/BlueBrain/BluePyOpt/blob/master/Makefile

https://github.com/BlueBrain/BluePyOpt/blob/master/tox.ini#L21

The nose website says:

https://nose.readthedocs.io/en/latest/

"Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2."

Deprecation of nose in Fedora: https://fedoraproject.org/wiki/Changes/DeprecateNose

Alternatives
py.test or nose2 (but nose2 doesn't seem to be at par with nose or py.test)

# Additional context

This came up while working on including BluePyOpt in Fedora as part of the [NeuroFedora](neuro.fedoraproject.org) initiative.

**Comment by wvangeit** [comment]
This was fixed by https://github.com/BlueBrain/BluePyOpt/pull/359
