### ISSUE TITLE
Make `ipyparallel` and `scoop` optional

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/BluePyOpt#374]
A quick grep of the code suggests that `ipyparallel` and `scoop` could be made into optional dependencies.
This would make the package easier to install, and work around errors from the upstream `scoop`, for instance.

I propose adding an `extras_requires` to the `setup.py`, either called `parallelism` that adds both the libraries to the install, or `scoop` for adding scoop.

Thoughts?

**Comment by mgeplf** [comment]
This is partly in response to:
https://github.com/BlueBrain/spack/pull/1230#issuecomment-888175217

**Comment by wvangeit** [comment]
I don't think ipyparallel should be optional though, most users would be using ipyparallel, and I'd prefer to make loading things as easy as possible for the default user.

**Comment by wvangeit** [comment]
But scoop can indeed be removed

**Comment by mgeplf** [comment]
> I don't think ipyparallel should be optional though, most users would be using ipyparallel

I'm not a huge fan of having deps that aren't used, but ok.

> But scoop can indeed be removed

Removed, or put behind an `pip install bluepyopt[scoop]` flag?

**Comment by wvangeit** [comment]
yes, bluepyopt[scoop] would be good.
@AurelienJaquier or @anilbey could you have a look at this?

**Comment by mgeplf** [comment]
I'll do it, no problem.

**Comment by anilbey** [comment]
Thanks @mgeplf

**Comment by mgeplf** [comment]
Closed by: https://github.com/BlueBrain/BluePyOpt/pull/375
