### ISSUE TITLE
Relational objectives

### ISSUE THREAD

**Issue by INF-Rene** [BlueBrain/BluePyOpt#392]
Hi I'm working on a FS neuron model and so far my experience with BluePyOpt has been very smooth, thanks a lot!

As far as I could tell it is not possible to make a certain objective relational to another outcome or objective. 

In my case, what I want to achieve is that the AP in the proximal axon comes before the AP in the soma. Therefore it would be great to set the time_to_first_spike in the axon to be dependent on the time_to_first_spike outcome in the soma.

I went through the code and as far as I understand this is not possible with the current implementation. Or am I missing something? Is there any workaround that you could think of?

**Comment by DrTaDa** [comment]
Hello @INF-Rene,
Indeed, that is not possible with the current implementation.

To do so, one solution could be for you to create a custom Objective class that would inherite from ephys.objectives. EFeatureObjective.
This new class could contain 2 spike timing efeatures, and its calculate_feature_values and calculate_feature_scores method would need to be rewritten to first compute the two efeatures independently and then perform the check you want before returning a custom score and/or value.

**Comment by DrTaDa** [comment]
That's good to hear! That's a good implementation, we could add it to BluePyOpt.

I will close this issue for the time being.
