### ISSUE TITLE
Keep all simulated trace

### ISSUE THREAD

**Issue by bhmagic** [BlueBrain/BluePyOpt#407]
Hi,

Our lab is interested in keeping all the simulated traces (or at least features) during the optimization. 

Please let me know what would be the best way to do it.

Thank you!

Yuan-TIng Wu
Cedars Sinai Medical Center

**Comment by DrTaDa** [comment]
Hello, 

I see two possible way to do so. If you wish to save all of the traces during optimization, the class "Responses" has a method "to_csv" (https://github.com/BlueBrain/BluePyOpt/blob/1e78a882b578b761d3dfd45eb92d869ebf0fc380/bluepyopt/ephys/responses.py#L68). You could add a line during evaluation to call this method, for example in this function: https://github.com/BlueBrain/BluePyOpt/blob/1e78a882b578b761d3dfd45eb92d869ebf0fc380/bluepyopt/ephys/evaluators.py#L185

The other more practical solution is to modify the evolutionary strategy to save the checkpoint with a different name at every generation. This way you would be able to access all the past populations, and you will be able to recomputed the traces you want after the optimization. For example, if you use IBEA, this can be done by removing this condition https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/deapext/algorithms.py#L178 and changing the filename for it to include the current number of the generation.

**Comment by bhmagic** [comment]
Thank you for the response!!

Yuan-Ting Wu
________________________________

**Comment by bhmagic** [comment]
I put this line in the "evaluate_with_dicts" and it fit my need nicely

        pickle.dump( {"param_dict": param_dict, "response": responses}, open( "dump/"+str(uuid.uuid4()), "wb" ) )

Put it here just in case someone needs it in the future.
