### ISSUE TITLE
Me fail to get the feature AIS_initialtion to work

### ISSUE THREAD

**Issue by bhmagic** [BlueBrain/BluePyOpt#409]
Hi,

Before I begin, I want to thank you for all the work!

My current pipeline is modified from the L5-pyramidal example. 

I added
 
                elif location == 'AIS':
                    threshold = soma_threashhold
                    recording_names = {'': '%s.%s.v' % (protocol_name, 'soma'), 
                                        'location_AIS': '%s.AIS.v' % protocol_name}

to the evaluator and added an extra recording named "AIS" using ephys.locations.NrnSomaDistanceCompLocation on axon. 

After running, I was able to find xxx.AIS.v  as a response trace but the evaluator always comeback "Error calculating AP_begin_time"

What would be the best way to diagnose this? 

I know this has become a "please help me find my bug" situation, and I will appreciate any help here. 

Thank you!, Yuan-Ting Wu

**Comment by DrTaDa** [comment]
Hello @bhmagic, 

I guess that the snippet of code you shared was added there https://github.com/BlueBrain/BluePyOpt/blob/master/examples/l5pc/l5pc_evaluator.py#L125 ?

It is a bit difficult to diagnose the issue without having access to your script. However, I can suggest not to use several recordings for the same eFELFeature.
For example, for an eFELFeature located at the AIS, given how the l5pc example is built, the recording_names should be:
`recording_names = {'': '%s.AIS.v' % protocol_name}`

If you wish to also compute the eFELFeature at the soma, it is better to create a second one, which will have:
`recording_names = {'': '%s.%s.v' % (protocol_name, location)} `

Note that if you wish to add mechanisms to the AIS, BluePyOpt does not understand by default what the section AIS is. It needs to be explicitly defined when creating the CellModel object: https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/models.py#L72

(Btw, I am not sure if it plays a role in this but you have a typo in your variable name soma_threashhold)

Let me know if that helps.

**Comment by bhmagic** [comment]
@DrTaDa 
Thank you for the amazingly quick response.
1. Yes, that is the example I modified. 
2. Unfortunately, I think Efel needs both soma and AIS voltage to compute this feature. Not sure if it is true. 
https://efel.readthedocs.io/en/latest/eFeatures.html#libv5-check-aisinitiation

3. My AIS was created with soma distance on 'axon'  (I see some put 'axonal' here, I am not sure what is the difference, but I do get a trace at the end, so I was assuming it is fine)


Here is more of the script. Let me know if you need more to diagnose. 
Thank you in advance!!!

import os
import json

import bluepyopt.ephys as ephys


def define_protocols(protocal_file):
    """Define protocols"""

    protocol_definitions = json.load(open(protocal_file))
    protocols = {}

    soma_loc = ephys.locations.NrnSeclistCompLocation(
        name='soma',
        seclist_name='somatic',
        sec_index=0,
        comp_x=0.5)

    for protocol_name, protocol_definition in protocol_definitions.items():
        # By default include somatic recording
        somav_recording = ephys.recordings.CompRecording(
            name='%s.soma.v' %
            protocol_name,
            location=soma_loc,
            variable='v')

        recordings = [somav_recording]

        if 'extra_recordings' in protocol_definition:
            for recording_definition in protocol_definition['extra_recordings']:
                if recording_definition['type'] == 'somadistance':
                    location = ephys.locations.NrnSomaDistanceCompLocation(
                        name=recording_definition['name'],
                        soma_distance=recording_definition['somadistance'],
                        seclist_name=recording_definition['seclist_name'])
                    var = recording_definition['var']
                    recording = ephys.recordings.CompRecording(
                        name='%s.%s.%s' % (protocol_name, location.name, var),
                        location=location,
                        variable=recording_definition['var'])

                    recordings.append(recording)
                else:
                    raise Exception(
                        'Recording type %s not supported' %
                        recording_definition['type'])

        stimuli = []
        for stimulus_definition in protocol_definition['stimuli']:
            stimuli.append(ephys.stimuli.NrnSquarePulse(
                step_amplitude=stimulus_definition['amp'],
                step_delay=stimulus_definition['delay'],
                step_duration=stimulus_definition['duration'],
                location=soma_loc,
                total_duration=stimulus_definition['totduration']))

        protocols[protocol_name] = ephys.protocols.SweepProtocol(
            protocol_name,
            stimuli,
            recordings)

    return protocols


def define_fitness_calculator(protocols, feature_file,soma_threashhold,dend_threashhold):
    """Define fitness calculator"""

    feature_definitions = json.load(open(feature_file))

    objectives = []

    for protocol_name, locations in feature_definitions.items():
        for location, features in locations.items():
            for efel_feature_name, meanstd in features.items():
                feature_name = '%s.%s.%s' % (
                    protocol_name, location, efel_feature_name)
                stimulus = protocols[protocol_name].stimuli[0]

                stim_start = stimulus.step_delay

                if location == 'soma':
                    threshold = soma_threashhold
                    recording_names = {'': '%s.%s.v' % (protocol_name, location)}

                elif 'dend' in location:
                    threshold = dend_threashhold
                    recording_names = {'': '%s.%s.v' % (protocol_name, location)}

                elif 'axon' in location:
                    threshold = soma_threashhold                    
                    recording_names = {'': '%s.%s.v' % (protocol_name, location)}
                elif 'AIS' in location:
                    threshold = soma_threashhold
                    recording_names = {'': '%s.%s.v' % (protocol_name, 'soma')}
                    recording_names.update({'AIS': '%s.%s.v' % (protocol_name, location)})                    

                if protocol_name == 'bAP':
                    stim_end = stimulus.total_duration
                else:
                    stim_end = stimulus.step_delay + stimulus.step_duration

                feature = ephys.efeatures.eFELFeature(
                    feature_name,
                    efel_feature_name=efel_feature_name,
                    recording_names=recording_names,
                    stim_start=stim_start,
                    stim_end=stim_end,
                    exp_mean=meanstd[0],
                    exp_std=meanstd[1],
                    threshold=threshold)
                objective = ephys.objectives.SingletonObjective(
                    feature_name,
                    feature)
                objectives.append(objective)

    fitcalc = ephys.objectivescalculators.ObjectivesCalculator(objectives)

    return fitcalc

**Comment by DrTaDa** [comment]
Ah sorry, I didn't realise it was a non-standard feature.
I will ask my colleagues who use this feature and have a look.

**Comment by bhmagic** [comment]
I see @DrTaDa ,  Thank you for checking in depth!  Let me try the hacking. I will let you know how it goes.  

Many thanks!

YTW

**Comment by bhmagic** [comment]
Dear @DrTaDa ,

After I went through it, I realized that the class you made is nearly done!  

The score should be (like other binary features), 250 (bad) if soma fires first, 0 (good) if AIS fires first. 

You are definitely way more qualified than me to integrate it and test it in BluePyOpt.  
Can you make a test/fork version of the modified BluePyOpt for me? 

I think it can be good for it to be included in the official release at the end. 


Yuan-Ting Wu

**Comment by DrTaDa** [comment]
Hello, 

I do not think that it should be included into BluePyOpt as it is custom code specific to your project. If it were to be integrated into a package, it would be better to fix the feature in eFEL such that it works in BluePyOpt.

**Comment by bhmagic** [comment]
A quick update, I was testing Efel today, and it appears to be working. Here is my code (the trace file can be found on efel github example/simple)


import os
import efel

import numpy

# Use numpy to read the trace data from the txt file
data = numpy.loadtxt('example_trace1.txt')

# Time is the first column
time = data[:, 0]
# Voltage is the second column
voltage = data[:, 1]

# Now we will construct the datastructure that will be passed to eFEL

# A 'trace' is a dictionary
trace1 = {}

# Set the 'T' (=time) key of the trace
trace1['T'] = time
trace1['T;location_AIS'] = time

# Set the 'V' (=voltage) key of the trace
trace1['V'] = voltage
trace1['V;location_AIS'] = voltage

# Set the 'stim_start' (time at which a stimulus starts, in ms)
# key of the trace
# Warning: this need to be a list (with one element)
trace1['stim_start'] = [700]
trace1['stim_start;location_AIS'] = [700]

# Set the 'stim_end' (time at which a stimulus end) key of the trace
# Warning: this need to be a list (with one element)
trace1['stim_end'] = [2700]
trace1['stim_end;location_AIS'] = [2700]

# Multiple traces can be passed to the eFEL at the same time, so the
# argument should be a list
traces = [trace1]

# Now we pass 'traces' to the efel and ask it to calculate the feature
# values
traces_results = efel.getFeatureValues(traces,
                                        ['check_AISInitiation'])
traces_distances = efel.getDistance(trace1, 'check_AISInitiation', 1.0, 1.0)

**Comment by DrTaDa** [comment]
Hello @bhmagic,

Does it work if you define the eFELFeature with:
```
recording_names = {'': '%s.%s.v' % (protocol_name, 'soma'), 
                                    'location_AIS': '%s.AIS.v' % protocol_name}
```
And then do:
```
efeature.calculate_feature(responses, raise_warnings=False)
```
Where responses is a dict that contains your example traces as TimeVoltageResponse ? (https://github.com/BlueBrain/BluePyOpt/blob/dbe650c88ebddaa8b1f412e4669e27216b3a7392/bluepyopt/ephys/responses.py#L44)

**Comment by bhmagic** [comment]
Similar to what you suggested, this also work:



response_testing = json.load(open('770650205_stage_2_iteration_1_hof_responses.json'))
response_testing = response_testing[0]['responses']

protocol_name = '14'

recording_names = {'': '%s.%s.v' % (protocol_name, 'soma'), 
                                    'location_AIS': '%s.AIS.v' % protocol_name}

response_testing[recording_names['']]['voltage'] = voltage
response_testing[recording_names['']]['time'] = time
response_testing[recording_names['location_AIS']]['voltage'] = voltage
response_testing[recording_names['location_AIS']]['time'] = time



feature = ephys.efeatures.eFELFeature(
    'check_AISInitiation',
    efel_feature_name='check_AISInitiation',
    recording_names=recording_names,
    stim_start=700,
    stim_end=2700,
    exp_mean=1,
    exp_std=1,
    threshold=-20)

feature.calculate_feature(response_testing, raise_warnings=False)

**Comment by DrTaDa** [comment]
It still doesn't work during evaluation? For example, if you do:
```
responses = evaluator.run_protocols(protocols=evaluator.fitness_protocols.values(), param_values=your_params)
print(responses)
print(feature.calculate_feature(responses, raise_warnings=False))
```

**Comment by DrTaDa** [comment]
Using eFEL, I wasn't getting an error. But it was always returning None for the feature you wanted.

**Comment by bhmagic** [comment]
After a lot of messing around, I actually have the flag working,  

1. if the #count of AIS and the soma firings do not match or any of the firing is not AIS first, it return None instead of zero
2. When there is no firing (sub threshold), it yells "Error calculating AP_begin_time"  and return None

So, the reason I got None for all HOF models is not because the feature not working, it might be the rapid firing or not firing make the flag false all the time.

Cheers,....Thank you for helping!! :-) 

YTW

**Comment by DrTaDa** [comment]
Interesting ! 
Good look with your model creation then :)
