### ISSUE TITLE
Useless dependency of future

### ISSUE THREAD

**Issue by frenzymadness** [BlueBrain/BluePyOpt#471]
Hello. I see that the project depends on future.
https://github.com/BlueBrain/BluePyOpt/blob/6aa893757e50a96a7e638d1c72a04f97424a2a21/setup.py#L55
I can find only a single usage of it in the codebase.
https://github.com/BlueBrain/BluePyOpt/blob/6aa893757e50a96a7e638d1c72a04f97424a2a21/bluepyopt/deapext/tools/selIBEA.py#L5
Do you think it's still useful? I'm asking because future is broken with the latest Python 3.12 and will be even more with 3.13 so it might be a good idea to get rid of it.

**Comment by AurelienJaquier** [comment]
Thank you for bringing up this Issue @frenzymadness !
I removed future in PR #473, so I will consider this fixed.
